#!/bin/bash

echo "🚀 NexaCore Custom Domain Deployment Status"
echo "=========================================="
echo ""
echo "Domain: nexacoreconsultancy.com"
echo "Repository: gautamanand22/NexaCore"
echo "Deployment: GitHub Pages"
echo ""
echo "📋 Next Steps for you:"
echo ""
echo "1. 🌐 Configure DNS in Namecheap:"
echo "   - Login to Namecheap account"
echo "   - Go to Domain List → Manage → Advanced DNS"
echo "   - Add CNAME record:"
echo "     Type: CNAME"
echo "     Host: www"
echo "     Value: gautamanand22.github.io"
echo "     TTL: Automatic"
echo ""
echo "   - Add CNAME for root domain:"
echo "     Type: CNAME"
echo "     Host: @"  
echo "     Value: gautamanand22.github.io"
echo "     TTL: Automatic"
echo ""
echo "2. 🔧 Configure GitHub Pages:"
echo "   - Go to: https://github.com/gautamanand22/NexaCore/settings/pages"
echo "   - Under 'Custom domain', enter: nexacoreconsultancy.com"
echo "   - Check 'Enforce HTTPS'"
echo "   - Save"
echo ""
echo "3. ⏱️  Wait for deployment:"
echo "   - GitHub Actions should complete in 2-3 minutes"
echo "   - DNS propagation may take 5-30 minutes"
echo "   - Check deployment at: https://github.com/gautamanand22/NexaCore/actions"
echo ""
echo "4. 🎉 Test your site:"
echo "   - Visit: https://nexacoreconsultancy.com"
echo "   - Check HTTPS is working (green lock)"
echo ""
echo "📚 Full guide: See CUSTOM_DOMAIN_SETUP.md"
echo ""
echo "✅ All files configured and pushed successfully!"
