#!/bin/bash

echo "🌐 NAMECHEAP DNS CONFIGURATION CHECKLIST"
echo "========================================"
echo ""
echo "Domain: nexacoreconsultancy.com"
echo "Target: GitHub Pages (gautamanand22.github.io)"
echo ""
echo "📝 STEP-BY-STEP CHECKLIST:"
echo ""
echo "□ Step 1: Login to Namecheap"
echo "  └─ Go to namecheap.com and sign in"
echo ""
echo "□ Step 2: Navigate to Domain"
echo "  └─ Domain List → nexacoreconsultancy.com → Manage"
echo ""
echo "□ Step 3: Open DNS Settings" 
echo "  └─ Click 'Advanced DNS' tab"
echo ""
echo "□ Step 4: Delete Existing Records"
echo "  └─ Remove any A records with Host: @"
echo "  └─ Remove any CNAME records with Host: www"
echo ""
echo "□ Step 5: Add CNAME Record #1"
echo "  └─ Type: CNAME"
echo "  └─ Host: @"
echo "  └─ Value: gautamanand22.github.io."
echo "  └─ TTL: Automatic"
echo ""
echo "□ Step 6: Add CNAME Record #2"
echo "  └─ Type: CNAME"
echo "  └─ Host: www"
echo "  └─ Value: gautamanand22.github.io."
echo "  └─ TTL: Automatic"
echo ""
echo "□ Step 7: Save Changes"
echo "  └─ Click 'Save All Changes'"
echo ""
echo "□ Step 8: Wait for Propagation"
echo "  └─ Wait 15-30 minutes"
echo ""
echo "🔍 VERIFICATION:"
echo "□ Check DNS: https://dnschecker.org"
echo "□ Test site: https://nexacoreconsultancy.com"
echo ""
echo "⚠️  IMPORTANT REMINDERS:"
echo "• Include the PERIOD at end: gautamanand22.github.io."
echo "• Use CNAME records, NOT A records"
echo "• Delete conflicting records first"
echo "• Wait 15-30 minutes for propagation"
echo ""
echo "📞 Need help? Namecheap has 24/7 live chat support!"
echo ""
echo "✅ After DNS is configured, continue with GitHub Pages setup"
